// Atacantes y jugadores goleadores del Mundial FIFA 2026
// Fuente: convocatorias oficiales confirmadas (mayo 2026)
// teamName debe coincidir con el nombre en la tabla teams (openfootball)

export interface Player {
  name: string
  teamName: string
}

export const WORLD_CUP_2026_PLAYERS: Player[] = [
  // ── Group A ──────────────────────────────────────────────
  { name: 'Santiago Giménez',      teamName: 'Mexico' },
  { name: 'Raúl Jiménez',          teamName: 'Mexico' },
  { name: 'Roberto Alvarado',      teamName: 'Mexico' },
  { name: 'Alexis Vega',           teamName: 'Mexico' },
  { name: 'Percy Tau',             teamName: 'South Africa' },
  { name: 'Lyle Foster',           teamName: 'South Africa' },
  { name: 'Evidence Makgopa',      teamName: 'South Africa' },
  { name: 'Son Heung-min',         teamName: 'South Korea' },
  { name: 'Cho Gue-sung',          teamName: 'South Korea' },
  { name: 'Hwang Hee-chan',        teamName: 'South Korea' },
  { name: 'Oh Hyeon-gyu',          teamName: 'South Korea' },
  { name: 'Patrik Schick',         teamName: 'Czech Republic' },
  { name: 'Adam Hlozek',           teamName: 'Czech Republic' },
  { name: 'Tomas Soucek',          teamName: 'Czech Republic' },

  // ── Group B ──────────────────────────────────────────────
  { name: 'Edin Džeko',            teamName: 'Bosnia & Herzegovina' },
  { name: 'Ermedin Demirovic',     teamName: 'Bosnia & Herzegovina' },
  { name: 'Jonathan David',        teamName: 'Canada' },
  { name: 'Cyle Larin',            teamName: 'Canada' },
  { name: 'Tajon Buchanan',        teamName: 'Canada' },
  { name: 'Lucas Cavallini',       teamName: 'Canada' },
  { name: 'Akram Afif',            teamName: 'Qatar' },
  { name: 'Almoez Ali',            teamName: 'Qatar' },
  { name: 'Breel Embolo',          teamName: 'Switzerland' },
  { name: 'Noah Okafor',           teamName: 'Switzerland' },
  { name: 'Ruben Vargas',          teamName: 'Switzerland' },
  { name: 'Zeki Amdouni',          teamName: 'Switzerland' },

  // ── Group C ──────────────────────────────────────────────
  { name: 'Vinicius Jr.',          teamName: 'Brazil' },
  { name: 'Neymar',                teamName: 'Brazil' },
  { name: 'Raphinha',              teamName: 'Brazil' },
  { name: 'Endrick',               teamName: 'Brazil' },
  { name: 'Gabriel Martinelli',    teamName: 'Brazil' },
  { name: 'Matheus Cunha',         teamName: 'Brazil' },
  { name: 'Igor Thiago',           teamName: 'Brazil' },
  { name: 'Youssef En-Nesyri',     teamName: 'Morocco' },
  { name: 'Hakim Ziyech',          teamName: 'Morocco' },
  { name: 'Soufiane Rahimi',       teamName: 'Morocco' },
  { name: 'Ayoub El Kaabi',        teamName: 'Morocco' },
  { name: 'Che Adams',             teamName: 'Scotland' },
  { name: 'Lyndon Dykes',          teamName: 'Scotland' },
  { name: 'Lawrence Shankland',    teamName: 'Scotland' },
  { name: 'Frantzdy Pierrot',      teamName: 'Haiti' },
  { name: 'Duckens Nazon',         teamName: 'Haiti' },

  // ── Group D ──────────────────────────────────────────────
  { name: 'Mathew Leckie',         teamName: 'Australia' },
  { name: 'Adam Taggart',          teamName: 'Australia' },
  { name: 'Mitchell Duke',         teamName: 'Australia' },
  { name: 'Miguel Almirón',        teamName: 'Paraguay' },
  { name: 'Julio Enciso',          teamName: 'Paraguay' },
  { name: 'Arda Güler',            teamName: 'Turkey' },
  { name: 'Kenan Yıldız',          teamName: 'Turkey' },
  { name: 'Baris Alper Yilmaz',    teamName: 'Turkey' },
  { name: 'Christian Pulisic',     teamName: 'USA' },
  { name: 'Ricardo Pepi',          teamName: 'USA' },
  { name: 'Folarin Balogun',       teamName: 'USA' },
  { name: 'Tim Weah',              teamName: 'USA' },

  // ── Group E ──────────────────────────────────────────────
  { name: 'Florian Wirtz',         teamName: 'Germany' },
  { name: 'Jamal Musiala',         teamName: 'Germany' },
  { name: 'Kai Havertz',           teamName: 'Germany' },
  { name: 'Leroy Sané',            teamName: 'Germany' },
  { name: 'Nick Woltemade',        teamName: 'Germany' },
  { name: 'Deniz Undav',           teamName: 'Germany' },
  { name: 'Maximilian Beier',      teamName: 'Germany' },
  { name: 'Jamie Leweling',        teamName: 'Germany' },
  { name: 'Sébastien Haller',      teamName: 'Ivory Coast' },
  { name: 'Simon Adingra',         teamName: 'Ivory Coast' },
  { name: 'Wilfried Zaha',         teamName: 'Ivory Coast' },
  { name: 'Enner Valencia',        teamName: 'Ecuador' },
  { name: 'Moisés Caicedo',        teamName: 'Ecuador' },
  { name: 'Ángel Mena',            teamName: 'Ecuador' },
  { name: 'Leandro Bacuna',        teamName: 'Curaçao' },

  // ── Group F ──────────────────────────────────────────────
  { name: 'Cody Gakpo',            teamName: 'Netherlands' },
  { name: 'Memphis Depay',         teamName: 'Netherlands' },
  { name: 'Wout Weghorst',         teamName: 'Netherlands' },
  { name: 'Donyell Malen',         teamName: 'Netherlands' },
  { name: 'Noa Lang',              teamName: 'Netherlands' },
  { name: 'Brian Brobbey',         teamName: 'Netherlands' },
  { name: 'Crysencio Summerville', teamName: 'Netherlands' },
  { name: 'Viktor Gyökeres',       teamName: 'Sweden' },
  { name: 'Alexander Isak',        teamName: 'Sweden' },
  { name: 'Dejan Kulusevski',      teamName: 'Sweden' },
  { name: 'Takumi Minamino',       teamName: 'Japan' },
  { name: 'Ritsu Doan',            teamName: 'Japan' },
  { name: 'Ayase Ueda',            teamName: 'Japan' },
  { name: 'Kaoru Mitoma',          teamName: 'Japan' },
  { name: 'Youssef Msakni',        teamName: 'Tunisia' },
  { name: 'Seifeddine Jaziri',     teamName: 'Tunisia' },

  // ── Group G ──────────────────────────────────────────────
  { name: 'Romelu Lukaku',         teamName: 'Belgium' },
  { name: 'Lois Openda',           teamName: 'Belgium' },
  { name: 'Leandro Trossard',      teamName: 'Belgium' },
  { name: 'Dodi Lukebakio',        teamName: 'Belgium' },
  { name: 'Mohamed Salah',         teamName: 'Egypt' },
  { name: 'Omar Marmoush',         teamName: 'Egypt' },
  { name: 'Mostafa Mohamed',       teamName: 'Egypt' },
  { name: 'Mehdi Taremi',          teamName: 'Iran' },
  { name: 'Sardar Azmoun',         teamName: 'Iran' },
  { name: 'Karim Ansarifard',      teamName: 'Iran' },
  { name: 'Chris Wood',            teamName: 'New Zealand' },
  { name: 'Kosta Barbarouses',     teamName: 'New Zealand' },

  // ── Group H ──────────────────────────────────────────────
  // Spain: Morata NOT selected (confirmed exclusión)
  { name: 'Lamine Yamal',          teamName: 'Spain' },
  { name: 'Nico Williams',         teamName: 'Spain' },
  { name: 'Mikel Oyarzabal',       teamName: 'Spain' },
  { name: 'Dani Olmo',             teamName: 'Spain' },
  { name: 'Ferran Torres',         teamName: 'Spain' },
  { name: 'Yeremy Pino',           teamName: 'Spain' },
  { name: 'Borja Iglesias',        teamName: 'Spain' },
  { name: 'Darwin Núñez',          teamName: 'Uruguay' },
  { name: 'Luis Suárez',           teamName: 'Uruguay' },
  { name: 'Facundo Pellistri',     teamName: 'Uruguay' },
  { name: 'Maximiliano Araújo',    teamName: 'Uruguay' },
  { name: 'Saleh Al-Shehri',       teamName: 'Saudi Arabia' },
  { name: 'Firas Al-Buraikan',     teamName: 'Saudi Arabia' },
  { name: 'Ryan Mendes',           teamName: 'Cape Verde' },
  { name: 'Garry Rodrigues',       teamName: 'Cape Verde' },

  // ── Group I ──────────────────────────────────────────────
  { name: 'Kylian Mbappé',         teamName: 'France' },
  { name: 'Marcus Thuram',         teamName: 'France' },
  { name: 'Ousmane Dembélé',       teamName: 'France' },
  { name: 'Bradley Barcola',       teamName: 'France' },
  { name: 'Michael Olise',         teamName: 'France' },
  { name: 'Désiré Doué',           teamName: 'France' },
  { name: 'Rayan Cherki',          teamName: 'France' },
  { name: 'Jean-Philippe Mateta',  teamName: 'France' },
  { name: 'Erling Haaland',        teamName: 'Norway' },
  { name: 'Alexander Sørloth',     teamName: 'Norway' },
  { name: 'Kasper Dolberg',        teamName: 'Norway' },
  { name: 'Sadio Mané',            teamName: 'Senegal' },
  { name: 'Ismaila Sarr',          teamName: 'Senegal' },
  { name: 'Boulaye Dia',           teamName: 'Senegal' },
  { name: 'Nicolas Jackson',       teamName: 'Senegal' },
  { name: 'Mohanad Ali',           teamName: 'Iraq' },

  // ── Group J ──────────────────────────────────────────────
  // Argentina: Di María retirado, Dybala no convocado
  { name: 'Lionel Messi',          teamName: 'Argentina' },
  { name: 'Lautaro Martínez',      teamName: 'Argentina' },
  { name: 'Julián Álvarez',        teamName: 'Argentina' },
  { name: 'Giuliano Simeone',      teamName: 'Argentina' },
  { name: 'Islam Slimani',         teamName: 'Algeria' },
  { name: 'Baghdad Bounedjah',     teamName: 'Algeria' },
  { name: 'Riyad Mahrez',          teamName: 'Algeria' },
  { name: 'Marko Arnautovic',      teamName: 'Austria' },
  { name: 'Christoph Baumgartner', teamName: 'Austria' },
  { name: 'Patrick Wimmer',        teamName: 'Austria' },
  { name: 'Michael Gregoritsch',   teamName: 'Austria' },
  { name: 'Ahmad Rikad',           teamName: 'Jordan' },

  // ── Group K ──────────────────────────────────────────────
  { name: 'Cristiano Ronaldo',     teamName: 'Portugal' },
  { name: 'Rafael Leão',           teamName: 'Portugal' },
  { name: 'Gonçalo Ramos',         teamName: 'Portugal' },
  { name: 'João Félix',            teamName: 'Portugal' },
  { name: 'Pedro Neto',            teamName: 'Portugal' },
  { name: 'Francisco Conceição',   teamName: 'Portugal' },
  { name: 'Gonçalo Guedes',        teamName: 'Portugal' },
  { name: 'Luis Díaz',             teamName: 'Colombia' },
  { name: 'Rafael Santos Borré',   teamName: 'Colombia' },
  { name: 'Jhon Durán',            teamName: 'Colombia' },
  { name: 'Cucho Hernández',       teamName: 'Colombia' },
  { name: 'Eldor Shomurodov',      teamName: 'Uzbekistan' },
  { name: 'Dieumerci Mbokani',     teamName: 'DR Congo' },
  { name: 'Yannick Bolasie',       teamName: 'DR Congo' },

  // ── Group L ──────────────────────────────────────────────
  // England: Foden y Cole Palmer NO convocados por Tuchel
  { name: 'Harry Kane',            teamName: 'England' },
  { name: 'Bukayo Saka',           teamName: 'England' },
  { name: 'Marcus Rashford',       teamName: 'England' },
  { name: 'Ollie Watkins',         teamName: 'England' },
  { name: 'Noni Madueke',          teamName: 'England' },
  { name: 'Anthony Gordon',        teamName: 'England' },
  { name: 'Ivan Toney',            teamName: 'England' },
  { name: 'Andrej Kramarić',       teamName: 'Croatia' },
  { name: 'Bruno Petković',        teamName: 'Croatia' },
  { name: 'Ivan Perišić',          teamName: 'Croatia' },
  { name: 'Mohammed Kudus',        teamName: 'Ghana' },
  { name: 'Jordan Ayew',           teamName: 'Ghana' },
  { name: 'Antoine Semenyo',       teamName: 'Ghana' },
  { name: 'Rolando Blackburn',     teamName: 'Panama' },
  { name: 'Gabriel Torres',        teamName: 'Panama' },
]
